<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TestMetadataPluginV7</RootNamespace>
    <AssemblyName>TestMetadataPluginV7</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PlayniteSDK.V7\Playnite.SDK.V7.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
