<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>TestGameLibrary</RootNamespace>
    <AssemblyName>TestGameLibrary</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PlayniteSDK\Playnite.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Resources\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
